# Generated by Django 5.0.14 on 2026-08-08 15:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                ("broker", models.CharField(blank=True, max_length=100)),
                (
                    "last_trade_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_whatsapp", models.BooleanField(default=False)),
                ("notify_telegram", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["account_name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Days after the last trade when the reminder was sent."
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="sent", max_length=20)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="trades.tradingaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reminderhistory",
            constraint=models.UniqueConstraint(
                fields=("account", "day_number", "channel"),
                name="unique_reminder_per_account_day_channel",
            ),
        ),
    ]
