# Generated by Django 5.0.14 on 2026-08-08 17:33

import trades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_list",
                    models.JSONField(
                        default=list,
                        help_text="List of day numbers (after last trade) on which to send reminders.",
                        validators=[trades.models.validate_reminder_days],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reminder schedule",
                "verbose_name_plural": "Reminder schedules",
            },
        ),
    ]
