# Generated by Django 5.0.14 on 2026-08-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_reminderschedule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reminderhistory",
            name="unique_reminder_per_account_day_channel",
        ),
        migrations.AddField(
            model_name="reminderhistory",
            name="slot_hour",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tradingaccount",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="The account number for this trading account (e.g. brokerage account number).",
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderhistory",
            constraint=models.UniqueConstraint(
                fields=("account", "day_number", "channel", "slot_hour"),
                name="unique_reminder_per_account_day_channel_slot",
            ),
        ),
    ]
