# Generated by Django 5.2.17 on 2026-09-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_update_site_domain_and_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_link_token",
            field=models.CharField(blank=True, db_index=True, max_length=43),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_link_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
